spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-micro-user
    username: postgres
    password: "*Gorakhpur1"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8081


